### ISSUE TITLE
Update to newest DynamX

### ISSUE THREAD

**Issue by gameusefly** [DynamXInc/BasicsAddon#10]
Is your feature request related to a problem? Please describe.
With the newest version of DynamX BasicsAddon doesn't work

Describe the solution you'd like
Update DynamX as dependency and fix breaking changes

**Comment by AymericBdy** [comment]
Solved in https://github.com/DynamXInc/BasicsAddon/commit/b3a3c40fc98a166863a5f0ad5b6cb3337165717a
