### ISSUE TITLE
Brake lights and reverse were not updated correctly

### ISSUE THREAD

**Issue by raphaelcolau** [DynamXInc/BasicsAddon#6]
### On branch 4.0
The stop and reverse lights have not been updated or not done.

### Versions:
- DynamX-4.0.0-beta-15-all
- BasicsAddon-1.0.4-for-DynamX-4.0.0

**Comment by AymericBdy** [comment]
Fixed in https://github.com/DynamXInc/BasicsAddon/commit/9bb208213cbd7d44c370a7b906b909db14d31b17
